server:
  port: 8081

spring:
  application:
    name: consumer1
  cloud:
    servicecomb:
      discovery:
        address: https://172.16.0.67:30100
        watch: false
      credentials:
        enabled: true
        accessKey: PSRRRPIMBQUYMEKDQM9L
        secretKey: sjjO4PiGjqaOEFbzx0i5VAaZbTDdHN7nEf56SJYJ
        project: cn-east-3
        akskCustomCipher: default
